/*                           /$$                                             **
**                          |__/                                             **
**        /$$$$$$$  /$$$$$$  /$$ /$$$$$$$  /$$   /$$                         **
**       /$$_____/ /$$__  $$| $$| $$__  $$| $$  | $$                         **
**      |  $$$$$$ | $$  \ $$| $$| $$  \ $$| $$  | $$   (c) Craig J Bishop    **
**       \____  $$| $$  | $$| $$| $$  | $$| $$  | $$   All rights reserved   **
**       /$$$$$$$/| $$$$$$$/| $$| $$  | $$|  $$$$$$$                         **
**      |_______/ | $$____/ |__/|__/  |__/ \____  $$   MIT License           **
**                | $$                     /$$  | $$                         **
**                | $$                    |  $$$$$$/                         **
**                |__/                     \______/                          **
**                                                                           **
** Permission is hereby granted, free of charge, to any person obtaining a   **
** copy of this software and associated documentation files (the             **
** "Software"), to deal in the Software without restriction, including       **
** without limitation the rights to use, copy, modify, merge, publish,       **
** distribute, sublicense, and/or sell copies of the Software, and to permit **
** persons to whom the Software is furnished to do so, subject to the        **
** following conditions:                                                     **
**                                                                           **
** The above copyright notice and this permission notice shall be included   **
** in all copies or substantial portions of the Software.                    **
**                                                                           **
** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS   **
** OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF                **
** MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN **
** NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,  **
** DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR     **
** OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE **
** USE OR OTHER DEALINGS IN THE SOFTWARE.                                    */

package spiny.dram

import spinal.core._
import spinal.lib._
import spinal.lib.bus.amba4.axi._
import spinal.lib.bus.wishbone._

/**
 * LiteDRAM controller BlackBox
 *
 * Wraps the Verilog generated by LiteDRAM with a SpinalHDL interface.
 * The Verilog is generated by the FuseSoC litedram generator.
 *
 * @param config LiteDRAM configuration parameters (with user ports populated)
 * @param sim LiteDRAM sim mode with internal DRAM model
 */
case class LiteDram(
  config: LiteDramConfig,
  sim: Boolean = false
) extends BlackBox {

  // Set the module name to match generated Verilog
  setDefinitionName(config.name)

  val io = new Bundle {
    // Input clock and reset (for internal PLL)
    val clk = in Bool() setName("clk")
    val rst = (!sim) generate {
      in Bool() setName("rst")
    }

    // User clock domain outputs
    val userClk = out Bool() setName("user_clk")
    val userRst = out Bool() setName("user_rst")

    // Status outputs
    val pllLocked = (!sim) generate {
      out Bool() setName("pll_locked")
    }
    val initDone = out Bool() setName("init_done")
    val initError = out Bool() setName("init_error")

    // Wishbone control bus
    val wbCtrl = slave(Wishbone(WishboneConfig(
      addressWidth = 30,
      dataWidth = 32,
      selWidth = 4,
      useSTALL = false,
      useLOCK = false,
      useERR = true,
      useRTY = false,
      useBTE = true,
      useCTI = true
    )))
    wbCtrl.CYC.setName("wb_ctrl_cyc")
    wbCtrl.STB.setName("wb_ctrl_stb")
    wbCtrl.ACK.setName("wb_ctrl_ack")
    wbCtrl.WE.setName("wb_ctrl_we")
    wbCtrl.ADR.setName("wb_ctrl_adr")
    wbCtrl.DAT_MISO.setName("wb_ctrl_dat_r")
    wbCtrl.DAT_MOSI.setName("wb_ctrl_dat_w")
    wbCtrl.SEL.setName("wb_ctrl_sel")
    wbCtrl.ERR.setName("wb_ctrl_err")
    wbCtrl.BTE.setName("wb_ctrl_bte")
    wbCtrl.CTI.setName("wb_ctrl_cti")

    // AXI user ports
    val axiUserPorts = config.userPorts.map { case (portName, portConfig) =>
      val axiConfig = Axi4Config(
        addressWidth = config.axiPortAddressWidth,
        dataWidth = portConfig.dataWidth,
        idWidth = portConfig.idWidth,
        useLock = false, useRegion = false,
        useCache = false, useProt = false, useQos = false
      )
      val port = slave(Axi4(axiConfig))
      LiteDram.setAxiLiteDramNames(port, portName)
      portName -> port
    }

    // DDR physical interface
    val dram = (!sim) generate {
      config.memType match {
        case DramMemType.Sdr =>
          master(SdrDramIo(
            addressWidth = config.addressWidth,
            bankAddressWidth = config.bankAddressWidth,
            dataWidth = config.ddrDataWidth,
            withChipSelects = config.withChipSelects
          ).setLiteDramNames())
        case DramMemType.Ddr2 =>
          master(Ddr2Io(
            addressWidth = config.addressWidth,
            bankAddressWidth = config.bankAddressWidth,
            dataWidth = config.ddrDataWidth,
            numRanks = config.numRanks,
            withChipSelects = config.withChipSelects
          ).setLiteDramNames())
        case DramMemType.Ddr3 =>
          master(Ddr3Io(
            addressWidth = config.addressWidth,
            bankAddressWidth = config.bankAddressWidth,
            dataWidth = config.ddrDataWidth,
            numRanks = config.numRanks,
            withChipSelects = config.withChipSelects
          ).setLiteDramNames())
        case DramMemType.Ddr4 =>
          master(Ddr4Io(
            addressWidth = config.addressWidth,
            bankAddressWidth = config.bankAddressWidth,
            bankGroupWidth = 2,
            dataWidth = config.ddrDataWidth,
            numRanks = config.numRanks,
            withChipSelects = config.withChipSelects
          ).setLiteDramNames())
      }
    }

    val simTrace = sim generate {
      in Bool() setName("sim_trace")
    }
  }

  // Map IO names to match LiteDRAM's generated Verilog
  mapCurrentClockDomain(io.clk, io.rst)
  noIoPrefix()

  /**
   * ClockDomain for the user clock.
   *
   * This clock domain should be used for logic interfacing with LiteDram.
   * The frequency is taken from the config to match what LiteDRAM generates.
   */
  val userClockDomain = ClockDomain(
    clock = io.userClk,
    reset = io.userRst,
    config = ClockDomainConfig(
      clockEdge = RISING,
      resetKind = SYNC,
    ),
    frequency = FixedFrequency(config.userClkFreq)
  )
}

object LiteDram {
  /**
   * Rename Axi4 sub-signals to match LiteDRAM's Verilog naming convention
   */
  private def setAxiLiteDramNames(port: Axi4, portName: String): Unit = {
    val p = s"user_port_${portName}"
    // AR
    port.ar.valid.setName(s"${p}_arvalid")
    port.ar.ready.setName(s"${p}_arready")
    port.ar.addr.setName(s"${p}_araddr")
    port.ar.id.setName(s"${p}_arid")
    port.ar.len.setName(s"${p}_arlen")
    port.ar.size.setName(s"${p}_arsize")
    port.ar.burst.setName(s"${p}_arburst")
    // AW
    port.aw.valid.setName(s"${p}_awvalid")
    port.aw.ready.setName(s"${p}_awready")
    port.aw.addr.setName(s"${p}_awaddr")
    port.aw.id.setName(s"${p}_awid")
    port.aw.len.setName(s"${p}_awlen")
    port.aw.size.setName(s"${p}_awsize")
    port.aw.burst.setName(s"${p}_awburst")
    // W
    port.w.valid.setName(s"${p}_wvalid")
    port.w.ready.setName(s"${p}_wready")
    port.w.data.setName(s"${p}_wdata")
    port.w.strb.setName(s"${p}_wstrb")
    port.w.last.setName(s"${p}_wlast")
    // R
    port.r.valid.setName(s"${p}_rvalid")
    port.r.ready.setName(s"${p}_rready")
    port.r.data.setName(s"${p}_rdata")
    port.r.id.setName(s"${p}_rid")
    port.r.resp.setName(s"${p}_rresp")
    port.r.last.setName(s"${p}_rlast")
    // B
    port.b.valid.setName(s"${p}_bvalid")
    port.b.ready.setName(s"${p}_bready")
    port.b.id.setName(s"${p}_bid")
    port.b.resp.setName(s"${p}_bresp")
  }

  /**
   * Create the appropriate DRAM physical interface bundle based on memory type
   */
  def createDramIo(config: LiteDramConfig): Bundle with IMasterSlave = {
    config.memType match {
      case DramMemType.Sdr =>
        SdrDramIo(
          addressWidth = config.addressWidth,
          bankAddressWidth = config.bankAddressWidth,
          dataWidth = config.ddrDataWidth,
          withChipSelects = config.withChipSelects
        )
      case DramMemType.Ddr2 =>
        Ddr2Io(
          addressWidth = config.addressWidth,
          bankAddressWidth = config.bankAddressWidth,
          dataWidth = config.ddrDataWidth,
          numRanks = config.numRanks,
          withChipSelects = config.withChipSelects
        )
      case DramMemType.Ddr3 =>
        Ddr3Io(
          addressWidth = config.addressWidth,
          bankAddressWidth = config.bankAddressWidth,
          dataWidth = config.ddrDataWidth,
          numRanks = config.numRanks,
          withChipSelects = config.withChipSelects
        )
      case DramMemType.Ddr4 =>
        Ddr4Io(
          addressWidth = config.addressWidth,
          bankAddressWidth = config.bankAddressWidth,
          bankGroupWidth = 2,
          dataWidth = config.ddrDataWidth,
          numRanks = config.numRanks,
          withChipSelects = config.withChipSelects
        )
    }
  }
}
